language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-add .travis.php.ini
  - composer install
  - composer dumpautoload -o
  - php -r "\$map = include('vendor/composer/autoload_classmap.php'); echo('map=['.print_r(\$map['KnotLib\\ExceptionHandler\\Text\\TextDebugtraceRenderer'],1)).']';"

script:
  - echo $(phpenv version-name)
  - curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-6.5.9.phar
  - phpunit --version
  - phpunit --configuration phpunit.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
